server:
  port: ${PORT:8222}
  address: 0.0.0.0

spring:
  application:
    name: go-api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: go-user-service
          uri: lb://GO-USER-SERVICE
          predicates:
            - Path=/api/v1/user/**
        - id: go-team-service
          uri: lb://GO-TEAM-SERVICE
          predicates:
            - Path=/api/v1/teams/**,/api/v1/invites/**
        - id: go-league-service
          uri: lb://GO-LEAGUE-SERVICE
          predicates:
            - Path=/api/v1/leagues/**
        - id: go-messaging-service-ws
          uri: lb:ws://GO-MESSAGING-SERVICE
          predicates:
            - Path=/api/v1/messaging/ws
          filters:
            - SetPath=/ws
        - id: go-messaging-service
          uri: lb://GO-MESSAGING-SERVICE
          predicates:
            - Path=/api/v1/messaging/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://one-magpie-92.clerk.accounts.dev

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:https://discovery-87v3.onrender.com/eureka}

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info
