spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/gameon_db
    url: jdbc:postgresql://dpg-d5jvc17pm1nc73cbddgg-a.virginia-postgres.render.com:5432/gameon_o3tt
#    username: username
    username: gameon_qn70_user
#    password: password
    password: bpKVIluvCJZZy3dzUD003cUZL4ZMPu7P
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    table: team_flyway_history
    locations: classpath:db/migration
    repair: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://one-magpie-92.clerk.accounts.dev

server:
  port: 8092

eureka:
  client:
    service-url:
      defaultZone: https://discovery-87v3.onrender.com/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
