spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/gameon_db
    url: jdbc:postgresql://dpg-d5jvc17pm1nc73cbddgg-a.virginia-postgres.render.com:5432/gameon_o3tt
#    username: username
    username: gameon_qn70_user
#    password: password
    password: bpKVIluvCJZZy3dzUD003cUZL4ZMPu7P
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://one-magpie-92.clerk.accounts.dev

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}

    consumer:
      group-id: ${KAFKA_GROUP_ID:gameon-service}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: "com.game.on.common.dto,com.game.on.*"
      spring.json.value.default.type: com.game.on.common.dto.PaymentDTO
      spring.json.use.type.headers: false
server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: https://discovery-87v3.onrender.com/eureka/