spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/gameon_db
    url: jdbc:postgresql://dpg-d5jvc17pm1nc73cbddgg-a.virginia-postgres.render.com:5432/gameon_o3tt
#    username: username
    username: gameon_qn70_user
#    password: password
    password: bpKVIluvCJZZy3dzUD003cUZL4ZMPu7P
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://one-magpie-92.clerk.accounts.dev

server:
  port: ${PORT:8090}
  address: 0.0.0.0

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:https://discovery-87v3.onrender.com/eureka}